
source 'https://rubygems.org'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes

gem 'ood_core', '~> 0.11'
gem 'sinatra'
gem 'minitest'
gem 'rake'
gem 'mocha'
gem 'rexml'

